version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
      - image: cimg/openjdk:17.0
      - image: circleci/postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD:

        working_directory: ~/setup
    steps:
      - checkout
      - run: rm busservices.sql || true
      - run: rm busservices-v1.sql || true
      - run: curl https://www.phpix.com/myNextBus/busservices-v1.sql --output busservices-v1.sql
      - run: sudo apt-get update && sudo apt-get install postgresql-client
      - run: psql -h 127.0.0.1 -U postgres  -c "create database busservices;"
      - run: psql -h 127.0.0.1 -U postgres busservices < ~/setup/busservices-v1.sql
      - run: mvn -B -DskipTests clean package

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: senzen/busservices-api
      - docker/push:
          image: senzen/busservices-api
  deploy:
    docker:
      - image: 'cimg/node:16.10'
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a busservices-api-devops
            heroku container:release web -a busservices-api-devops
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push


