version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8-jdk
      - image: cimg/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: 

    working_directory: ~/setup
    steps:
      - checkout
      - run: rm busservices.sql
      - run: wget https://github.com/senthil-zappz/busapi/blob/main/busservices.sql
      - run: sudo apt-get update && sudo apt-get install postgresql
      - run: psql -h 127.0.0.1 -U postgres postgres< ~/setup/busservices.sql
