version: 2
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      - image: circleci/postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: 

    working_directory: ~/setup
    steps:
      - checkout
      - run: rm busservices.sql || true
      - run: rm busservices-v1.sql || true
      - run: curl https://www.phpix.com/myNextBus/busservices-v1.sql --output busservices-v1.sql
      - run: sudo apt-get update && sudo apt-get install postgresql-client
      - run: psql -h 127.0.0.1 -U postgres  -c "create database busservices;"
      - run: psql -h 127.0.0.1 -U postgres busservices < ~/setup/busservices-v1.sql
      - run: mvn -B -DskipTests clean package

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn test

workflows:
  build:
    jobs:
      - build

  test:
    jobs:
      - test
      