version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: 

    working_directory: ~/setup
    steps:
      - checkout
      - run: rm busservices.sql
      - run: curl https://www.phpix.com/myNextBus/busservices.sql --output busservices.sql
      - run: sudo apt-get update && sudo apt-get install postgresql
      - run: psql -h 127.0.0.1 -U postgres postgres< ~/setup/busservices.sql
